set-window-option -g mode-keys vi
# setw -g clock-mode-colour yellow
set -g status-right '%Y-%m-%d %H:%M '
# CPU load
set -g status-right "CPU: #(uptime | awk -F'load average:' '{print $2}')"
# RAM laod
set -g status-right "RAM: #(free -m | awk '/Mem:/ {printf \"%.0f%%\", $3/$2*100}')"
